// generated by Go Code Generator(https://github.com/OhYee/gcg); DO NOT EDIT

package op

import ()

// OperatorType expression operator type
type OperatorType uint8

// operator constant
const (
	_ OperatorType = iota
	OperatorStr
	OperatorNot
	OperatorEqual
	OperatorNotEqual
	OperatorLessThan
	OperatorGreaterThan
	OperatorGreaterEqual
	OperatorLessEqual
	OperatorIn
	OperatorNotIn
	OperatorLike
	OperatorBetween
)

var operatorName = [...]string{
	"Unknown",
	"Str",
	"Not",
	"Equal",
	"NotEqual",
	"LessThan",
	"GreaterThan",
	"GreaterEqual",
	"LessEqual",
	"In",
	"NotIn",
	"Like",
	"Between",
}

func (ot OperatorType) String() string {
	if int(ot) > len(operatorName) {
		return "Unknown"
	}
	return operatorName[ot]
}
