// generated by Go Code Generator(https://github.com/OhYee/gcg); DO NOT EDIT

package op

import "testing"

func TestOperatorType_String(t *testing.T) {
	tests := []struct {
		name string
		ot   OperatorType
		want string
	}{
		{
			name: "Unknow",
			ot:   0xff,
			want: "Unknown",
		},
		{
			name: "Str",
			ot:   OperatorStr,
			want: "Str",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := tt.ot.String(); got != tt.want {
				t.Errorf("OperatorType.String() = %v, want %v", got, tt.want)
			}
		})
	}
}
