// Code generated by GCG. DO NOT EDIT.
// Go Code Generator 0.0.6 (https://github.com/OhYee/gcg)

package op

import ()

// OperatorType expression operator type
type OperatorType uint8

// operator constant
const (
	_ OperatorType = iota
	OperatorStr
	OperatorNot
	OperatorEqual
	OperatorNotEqual
	OperatorLessThan
	OperatorGreaterThan
	OperatorGreaterEqual
	OperatorLessEqual
	OperatorIn
	OperatorNotIn
	OperatorLike
	OperatorBetween
)

var operatorName = [...]string{
	"Unknown",
	"Str",
	"Not",
	"Equal",
	"NotEqual",
	"LessThan",
	"GreaterThan",
	"GreaterEqual",
	"LessEqual",
	"In",
	"NotIn",
	"Like",
	"Between",
}

func (co OperatorType) String() string {
	if int(co) > len(operatorName) {
		return "Unknown"
	}
	return operatorName[co]
}
